In [9]:
import os
import numpy as np
import pandas as pd
import torch
from matplotlib import pyplot as plt
from scipy.misc import imread, imresize
from torch.utils.data import Dataset, DataLoader
from utils import config

In [17]:
def resize(X):
    """
    Resizes the data partition X to the size specified in the config file.
    Uses bicubic interpolation for resizing.

    Returns:
        the resized images as a numpy array.
    """
    # TODO: Complete this function
    image_dim = config('image_dim')
    resized = imresize(X, (2, 2, 3), 'bicubic')
    # 

    return resized

In [18]:
X = np.random.random_sample((5,5,3))
X

array([[[0.42541674, 0.12041374, 0.44019702],
        [0.49041307, 0.28656772, 0.67137096],
        [0.01767678, 0.55269416, 0.29442429],
        [0.24306949, 0.30161574, 0.4512044 ],
        [0.52707996, 0.79808894, 0.36321   ]],

       [[0.06850087, 0.11870475, 0.09778801],
        [0.0204611 , 0.93853565, 0.10709976],
        [0.90621386, 0.3069947 , 0.78013601],
        [0.75477104, 0.82064949, 0.88443266],
        [0.45355119, 0.35845151, 0.46606287]],

       [[0.98573731, 0.59165825, 0.0728358 ],
        [0.32719057, 0.24065793, 0.9931465 ],
        [0.13133269, 0.27443783, 0.57532599],
        [0.04206506, 0.66079174, 0.45612498],
        [0.81856147, 0.27485494, 0.10869235]],

       [[0.71242795, 0.55448606, 0.52952268],
        [0.19307555, 0.97177512, 0.08112116],
        [0.61229321, 0.67997373, 0.18550798],
        [0.23424361, 0.50434794, 0.09592488],
        [0.51213763, 0.11105092, 0.3382647 ]],

       [[0.02282981, 0.80109332, 0.40603887],
        [0.24522731, 0.442

In [19]:
resize(X)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  # This is added back by InteractiveShellApp.init_path()


array([[[ 88, 103, 107],
        [116, 134, 129]],

       [[ 90, 161, 101],
        [104,  85, 107]]], dtype=uint8)

In [20]:
X

array([[[0.42541674, 0.12041374, 0.44019702],
        [0.49041307, 0.28656772, 0.67137096],
        [0.01767678, 0.55269416, 0.29442429],
        [0.24306949, 0.30161574, 0.4512044 ],
        [0.52707996, 0.79808894, 0.36321   ]],

       [[0.06850087, 0.11870475, 0.09778801],
        [0.0204611 , 0.93853565, 0.10709976],
        [0.90621386, 0.3069947 , 0.78013601],
        [0.75477104, 0.82064949, 0.88443266],
        [0.45355119, 0.35845151, 0.46606287]],

       [[0.98573731, 0.59165825, 0.0728358 ],
        [0.32719057, 0.24065793, 0.9931465 ],
        [0.13133269, 0.27443783, 0.57532599],
        [0.04206506, 0.66079174, 0.45612498],
        [0.81856147, 0.27485494, 0.10869235]],

       [[0.71242795, 0.55448606, 0.52952268],
        [0.19307555, 0.97177512, 0.08112116],
        [0.61229321, 0.67997373, 0.18550798],
        [0.23424361, 0.50434794, 0.09592488],
        [0.51213763, 0.11105092, 0.3382647 ]],

       [[0.02282981, 0.80109332, 0.40603887],
        [0.24522731, 0.442

In [21]:
X * 10

array([[[4.25416736, 1.20413742, 4.40197015],
        [4.90413071, 2.86567717, 6.71370961],
        [0.17676784, 5.52694163, 2.94424289],
        [2.43069485, 3.01615744, 4.51204395],
        [5.27079956, 7.98088944, 3.63209996]],

       [[0.68500865, 1.18704751, 0.97788011],
        [0.20461102, 9.38535645, 1.07099764],
        [9.06213862, 3.069947  , 7.80136008],
        [7.54771039, 8.20649487, 8.84432664],
        [4.53551192, 3.5845151 , 4.66062867]],

       [[9.85737313, 5.91658249, 0.72835797],
        [3.2719057 , 2.40657931, 9.93146498],
        [1.31332693, 2.74437831, 5.7532599 ],
        [0.42065059, 6.60791742, 4.56124984],
        [8.18561465, 2.74854942, 1.08692349]],

       [[7.12427954, 5.54486061, 5.29522675],
        [1.93075547, 9.71775116, 0.81121157],
        [6.12293209, 6.79973735, 1.85507977],
        [2.34243605, 5.04347944, 0.9592488 ],
        [5.12137631, 1.11050922, 3.38264702]],

       [[0.22829813, 8.01093315, 4.06038874],
        [2.45227307, 4.429

In [1]:
1e-4

0.0001